UISAUTHCOM-12 Ensure support for the passed tenantId value for manipulations in the context of a specific tenant
folio-org/stripes-authorization-components pull request #21
Opened 2024-08-16 07:16 UTC by usavkov-epam

## Purpose

https://folio-org.atlassian.net/browse/UISAUTHCOM-12

## Approach

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-08-20 11:27 UTC, SKarolFolio approved these changes

2024-08-20 13:39 UTC, zburke requested changes
Code changes LGTM. Thank you for implementing this consistently across all the hooks ❤️ . 

The only change is minor but important: `useChunkedCQLFetch` won't get support for the `tenantId` option (used by a few of these hooks) until stripes-core v10.2.0, which will be available in `@folio/stripes` `v9.2.0`, so we need to bump to that minimum version in the `peerDependencies` in `package.json`. Since we haven't released this repo yet, it doesn't matter that bumping a peer is a breaking change and we can leave the module version at 1.0.0.

2024-08-22 13:40 UTC, alisher-epam approved these changes

2024-08-22 18:52 UTC, zburke approved these changes

2024-08-23 06:05 UTC, merged